version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.9-buster
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "46:99:bd:8a:56:ae:07:3b:13:07:1b:a2:f4:dc:20:21"
      - run:
          command: |
            git config user.name "Tony Kelman"
            git config user.email "tony@kelman.net"
            ./$CIRCLE_BRANCH.sh
workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - venues
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - archive
    jobs:
      - build
  everytwentyminutes:
    triggers:
      - schedule:
          cron: "5,25,45 * * * *"
          filters:
            branches:
              only:
                - testing
    jobs:
      - build
