version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8-jessie
    steps:
      - checkout
      - run:
          command: |
            git config user.name "Tony Kelman"
            git config user.email "tony@kelman.net"
            ./thelist_archive.sh
